format = """[\\[](#6eb9f8)[fer](#ffffff)[@](#6eb9f8)[devrrior](#ffffff)[\\]](#6eb9f8) $character$python$directory$git_branch\
"""

add_newline = false

[character]
success_symbol = "[➜](bold #e4e0d7) "
error_symbol = "[➜](bold #ff786c) "

[directory]
style = "bold #ffffff"

[python]
format = '[(\($virtualenv\) )]($style)'
style = "#56b6c2 bold"

[git_branch]
style = "bold #c678dd"
